[pyspark] fix a minor typing bug
`from xgboost.spark import SparkXGBClassifier` will throw exception
when running on older pyspark (3.2.1) with the error msg

``` python
---> 16     arbitrary_params_dict: Param[Dict] = Param(
     17         Params._dummy(),
     18         "arbitrary_params_dict",
     19         "arbitrary_params_dict This parameter holds all of the additional parameters which are "
     20         "not exposed as the the XGBoost Spark estimator params but can be recognized by "
     21         "underlying XGBoost library. It is stored as a dictionary.",
     22     )

TypeError: 'type' object is not subscriptable
```

Change the typing to "Param[Dict]"