Drop support for deprecated CUDA architecture.
I can't upload the pip package due to maximum size reached.

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
File too large. Limit for project 'xgboost' is 200 MB. See https://pypi.org/help/#file-size-limit for more information.
```