Fix x86 release build in c_api.cc
Following error was fixed in x86 release build:
Error C2398: Element '4': conversion from 'xgboost::bst_ulong' to 'size_t' requires a narrowing conversion, xgboost\src\c_api\c_api.cc 738