Add explicit return type to `__device__` lambda
Fix the following error message:

```
error: static assertion failed: Attempt to use an extended __device__
lambda in a context that requires querying its return type in host
code. Use a named function object, an extended __host__ __device__
lambda, cuda::proclaim_return_type, or an extended __device__ lambda
with a trailing return type instead
([] __device__ (...) -> RETURN_TYPE {...}).
```